'use strict'

const products = [
    {
        id: 1_05,
        src_1: './images/content/gallery/1_05.avif',
        src_2: './images/content/products/1_05_02.avif',
        src_3: './images/content/products/1_05_03.avif',
        src_4: './images/content/products/1_05_04.avif',
        src_5: './images/content/products/1_05_05.avif',
        src_6: './images/content/products/1_05_06.avif',
        src_7: './images/content/products/1_05_07.avif',
        src_8: './images/content/products/1_05_08.avif',
        src_8: './images/content/products/1_05_09.avif',
        src_8: './images/content/products/1_05_10.avif',
        title: "Нож-подвеска",
        subtitle: "Сталь у12а",
        descriptionBlade: "Клинок: сталь у12а, твердость 61hrc.",
        descriptionHandle: "Рукоять: карельская берёза, поставка фибра, пропитка.",
        descriptionScabbard: "Ножны: сборная петля, кожаный шнур, кожа, покраска, пропитка, финиш.",
        filter: "knives-mini",
    },
    {
        id: 2_01,
        src_1: './images/content/gallery/2_01.avif',
        src_2: './images/content/products/2_01_02.avif',
        src_3: './images/content/products/2_01_03.avif',
        src_4: './images/content/products/2_01_04.avif',
        src_5: './images/content/products/2_01_05.avif',
        src_6: './images/content/products/2_01_06.avif',
        src_7: './images/content/products/2_01_07.avif',
        src_8: './images/content/products/2_01_08.avif',
        src_9: './images/content/products/2_01_09.avif',
        src_10: './images/content/products/2_01_10.avif',
        title: "Нож. Финка",
        subtitle: "Дамасская сталь",
        descriptionBlade: "Клинок: Дамасская сталь, закалка 60 hrc.",
        descriptionHandle: "Рукоять: Карельская берёза, чёрный граб, бронза.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка.",
        filter: "knives-traditional, damask-steel",
    },
    {
        id: 2_02,
        src_1: './images/content/gallery/2_02.avif',
        src_2: './images/content/products/2_02_02.avif',
        src_3: './images/content/products/2_02_03.avif',
        src_4: './images/content/products/2_02_04.avif',
        src_5: './images/content/products/2_02_05.avif',
        src_6: './images/content/products/2_02_06.avif',
        src_7: './images/content/products/2_02_07.avif',
        title: "Нож. Сборный",
        subtitle: "Сталь Bohler s390",
        descriptionBlade: "Клинок: сталь Bohler s390, 68 hrc.",
        descriptionHandle: "Рукоять: Аризонское железное дерево (Ironwood), больстер титан.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка.",
        filter: "knives-traditional",
    },
    {
        id: 2_03,
        src_1: './images/content/gallery/2_03.avif',
        src_2: './images/content/products/2_03_02.avif',
        src_3: './images/content/products/2_03_03.avif',
        src_4: './images/content/products/2_03_04.avif',
        src_5: './images/content/products/2_03_05.avif',
        src_6: './images/content/products/2_03_06.avif',
        src_7: './images/content/products/2_03_07.avif',
        src_8: './images/content/products/2_03_08.avif',
        src_9: './images/content/products/2_03_09.avif',
        title: "Нож",
        subtitle: "Cталь х12мф",
        descriptionBlade: "Клинок: сталь х12мф, обработка клинка stonewash, закалка 59 hrc.",
        descriptionHandle: "Рукоять: чёрный граб, рог лося, бронза, фибра, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка, рог лося, чёрный граб.",
        filter: "knives-traditional",
    },
    {
        id: 2_04,
        src_1: './images/content/gallery/2_04.avif',
        src_2: './images/content/products/2_04_02.avif',
        src_3: './images/content/products/2_04_03.avif',
        src_4: './images/content/products/2_04_04.avif',
        src_5: './images/content/products/2_04_05.avif',
        src_6: './images/content/products/2_04_06.avif',
        src_7: './images/content/products/2_04_07.avif',
        src_8: './images/content/products/2_04_08.avif',
        src_9: './images/content/products/2_04_09.avif',
        title: "Нож",
        subtitle: "Cталь 5160 (США)",
        descriptionBlade: "Клинок: сталь 5160 (США), закалка 57 hrc.",
        descriptionHandle: "Рукоять: дуб, дюралюминий, фибра, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка.",
        filter: "knives-traditional",
    },
    {
        id: 6_02,
        src_1: './images/content/products/6_02_01.avif',
        src_2: './images/content/products/6_02_02.avif',
        src_3: './images/content/products/6_02_03.avif',
        title: "Нож",
        subtitle: "Сталь шх15",
        descriptionBlade: "Клинок: сталь шх15 ,твердость 60hrc.",
        descriptionHandle: "Рукоять: карельская берёза с эффектом изменения цвета, патинированная бронза, проставка фибра, пропитка.",
        descriptionScabbard: "Ножны: кожа, вставка шкура змеи, покраска, пропитка, финиш.",
        filter: "knives-traditional",
    },
    {
        id: 2_12,
        src_1: './images/content/products/2_12_01.avif',
        src_2: './images/content/products/2_12_02.avif',
        src_3: './images/content/products/2_12_03.avif',
        src_4: './images/content/products/2_12_04.avif',
        src_5: './images/content/products/2_12_05.avif',
        src_6: './images/content/products/2_12_06.avif',
        src_7: './images/content/products/2_12_07.avif',
        src_8: './images/content/products/2_12_08.avif',
        src_9: './images/content/products/2_12_09.avif',
        title: "Нож",
        subtitle: "Дамасская сталь",
        descriptionBlade: "Клинок: дамаск, твердость 60hrc.",
        descriptionHandle: "Рукоять: платан, патинированная бронза, фибра, пропитка.",
        descriptionScabbard: "Ножны: разборные на браслет и футляр, кожа, кожа змеи, покраска, пропитка, финиш.",
        filter: "knives-traditional, damask-steel",
    },
    {
        id: 2_05,
        src_1: './images/content/products/2_05_03.avif',
        src_2: './images/content/products/2_05_02.avif',
        src_3: './images/content/gallery/2_05.avif',
        src_4: './images/content/products/2_05_04.avif',
        src_5: './images/content/products/2_05_05.avif',
        src_6: './images/content/products/2_05_06.avif',
        src_7: './images/content/products/2_05_07.avif',
        src_8: './images/content/products/2_05_08.avif',
        title: "Нож",
        subtitle: "Cталь 5160 (США)",
        descriptionBlade: "Клинок: сталь 5160 (США), закалка 57 hrc.",
        descriptionHandle: "Рукоять: дуб, мамонт, титан, фибра, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка.",
        filter: "knives-traditional",
    },
    {
        id: 2_09,
        src_1: './images/content/products/2_09_01.avif',
        src_2: './images/content/products/2_09_02.avif',
        src_3: './images/content/products/2_09_03.avif',
        src_4: './images/content/products/2_09_04.avif',
        src_5: './images/content/products/2_09_05.avif',
        src_6: './images/content/products/2_09_06.avif',
        src_7: './images/content/products/2_09_07.avif',
        title: "Нож. Трудоголик",
        subtitle: "Cталь х12мф",
        descriptionBlade: "Клинок: сталь х12мф, обработка клинка stonewash, закалка 59 hrc.",
        descriptionHandle: "Рукоять: Граб, Чёрный граб, бронза, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка.",
        filter: "knives-traditional",
    },
    {
        id: 1_03,
        src_1: './images/content/gallery/1_03.avif',
        src_2: './images/content/products/1_03_02.avif',
        src_3: './images/content/products/1_03_03.avif',
        src_4: './images/content/products/1_03_04.avif',
        src_5: './images/content/products/1_03_05.avif',
        src_6: './images/content/products/1_03_06.avif',
        src_7: './images/content/products/1_03_07.avif',
        src_8: './images/content/products/1_03_08.avif',
        title: "Нож-подвеска Птичка",
        subtitle: "Сталь 60с2а",
        descriptionBlade: "Клинок: сталь 60с2а, закалка 56 hrc.",
        descriptionHandle: "",
        descriptionScabbard: "Ножны: кожа, тиснение, покраска, пропитка.",
        filter: "knives-mini",
    },
    {
        id: 3_06,
        src_1: './images/content/gallery/3_06.avif',
        src_2: './images/content/products/3_06_02.avif',
        src_3: './images/content/products/3_06_03.avif',
        src_4: './images/content/products/3_06_04.avif',
        src_5: './images/content/products/3_06_05.avif',
        src_6: './images/content/products/3_06_06.avif',
        src_7: './images/content/products/3_06_07.avif',
        title: "Шеф-нож",
        subtitle: "Сталь 95х18",
        descriptionBlade: "Клинок: сталь 95х18, твердость 57hrc.",
        descriptionHandle: "Рукоять: падук, кавказский орех, поставка фибра, пропитка.",
        descriptionScabbard: "",
        filter: "knives-kitchen",
    },
    {
        id: 3_04,
        src_1: './images/content/gallery/3_04.avif',
        src_2: './images/content/products/3_04_02.avif',
        src_3: './images/content/products/3_04_03.avif',
        src_4: './images/content/products/3_04_04.avif',
        src_5: './images/content/products/3_04_05.avif',
        src_6: './images/content/products/3_04_06.avif',
        src_7: './images/content/products/3_04_07.avif',
        src_8: './images/content/products/3_04_08.avif',
        title: "Шеф-нож",
        subtitle: "Сталь 95х18",
        descriptionBlade: "Клинок: сталь 95х18, твердость 57hrc.",
        descriptionHandle: "Рукоять: карельская берёза, амарант, фибра, пропитка.",
        descriptionScabbard: "",
        filter: "knives-kitchen",
    },
    {
        id: 1_02,
        src_1: './images/content/gallery/1_02.avif',
        src_2: './images/content/products/1_02_02.avif',
        title: "Ножи-подвески",
        subtitle: "Сталь у12а",
        descriptionBlade: "Клинок: сталь у12а, закалка 61hrc.",
        descriptionHandle: "",
        descriptionScabbard: "Ножны: кожа, тиснение, покраска, пропитка.",
        filter: "knives-mini",
    },
    {
        id: 2_07,
        src_1: './images/content/products/2_07.avif',
        src_2: './images/content/products/2_07_02.avif',
        src_3: './images/content/products/2_07_03.avif',
        src_4: './images/content/products/2_07_04.avif',
        src_5: './images/content/products/2_07_05.avif',
        src_6: './images/content/products/2_07_06.avif',
        src_7: './images/content/products/2_07_07.avif',
        title: "Нож. Лёлик",
        subtitle: "Cталь х12мф",
        descriptionBlade: "Клинок: сталь х12мф, обработка клинка stonewash, закалка 59 hrc.",
        descriptionHandle: "Рукоять: Карельская берёза, падук, бронза, фибра, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка.",
        filter: "knives-traditional",
    },
    {
        id: 2_08,
        src_1: './images/content/products/2_08_01.avif',
        src_2: './images/content/products/2_08_02.avif',
        src_3: './images/content/products/2_08_03.avif',
        src_4: './images/content/products/2_08_04.avif',
        src_5: './images/content/products/2_08_05.avif',
        title: "Нож. Болик",
        subtitle: "Cталь х12мф",
        descriptionBlade: "Клинок: сталь х12мф, обработка клинка stonewash, закалка 59 hrc.",
        descriptionHandle: "Рукоять: Карельская берёза, микарта, бронза, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка.",
        filter: "knives-traditional",
    },
    {
        id: 2_06,
        src_1: './images/content/gallery/2_06.avif',
        src_2: './images/content/products/2_06_02.avif',
        src_3: './images/content/products/2_06_03.avif',
        src_4: './images/content/products/2_06_04.avif',
        src_5: './images/content/products/2_06_05.avif',
        src_6: './images/content/products/2_06_06.avif',
        src_7: './images/content/products/2_06_07.avif',
        src_8: './images/content/products/2_06_08.avif',
        src_9: './images/content/products/2_06_09.avif',
        src_10: './images/content/products/2_06_10.avif',
        title: "Нож. Финка",
        subtitle: "Cталь У8",
        descriptionBlade: "Клинок: сталь У8, воронение, закалка 60 hrc.",
        descriptionHandle: "Рукоять: карельская берёза, фибра, бронза.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка.",
        filter: "knives-traditional",
    },
    {
        id: 2_10,
        src_1: './images/content/products/2_10_01.avif',
        src_2: './images/content/products/2_10_02.avif',
        src_3: './images/content/products/2_10_03.avif',
        src_4: './images/content/products/2_10_04.avif',
        src_5: './images/content/products/2_10_05.avif',
        src_6: './images/content/products/2_10_06.avif',
        title: "Нож. Крыска",
        subtitle: "Cталь х12мф",
        descriptionBlade: "Клинок: сталь х12мф, обработка клинка stonewash, закалка 59 hrc.",
        descriptionHandle: "Рукоять: Чёрный граб, Карельская берёза, бронза, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка.",
        filter: "knives-traditional",
    },
    {
        id: 4_01,
        src_1: './images/content/gallery/4_01.avif',
        src_2: './images/content/products/4_01_02.avif',
        src_3: './images/content/products/4_01_03.avif',
        src_4: './images/content/products/4_01_04.avif',
        src_5: './images/content/products/4_01_05.avif',
        src_6: './images/content/products/4_01_06.avif',
        src_7: './images/content/products/4_01_07.avif',
        src_8: './images/content/products/4_01_08.avif',
        src_9: './images/content/products/4_01_09.avif',
        src_10: './images/content/products/4_01_10.avif',
        title: "Топорик",
        subtitle: "Сталь 60с2а",
        descriptionBlade: "Клинок: сталь 60с2а, закалка 55 hrc.",
        descriptionHandle: "Рукоять: Карельская берёза, амарант, фибра, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка.",
        filter: "other",
    },
    {
        id: 4_03,
        src_1: './images/content/gallery/4_03.avif',
        src_2: './images/content/products/4_03_02.avif',
        src_3: './images/content/products/4_03_03.avif',
        src_4: './images/content/products/4_03_04.avif',
        src_5: './images/content/products/4_03_05.avif',
        src_6: './images/content/products/4_03_06.avif',
        src_7: './images/content/products/4_03_07.avif',
        src_8: './images/content/products/4_03_08.avif',
        title: "Топорик",
        subtitle: "Сталь 60с2а",
        descriptionBlade: "Клинок: сталь 60с2а, закалка 55 hrc.",
        descriptionHandle: "Рукоять: карельская берёза, орех, фибра, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка.",
        filter: "other",
    },
    {
        id: 2_11,
        src_1: './images/content/products/2_11_03.avif',
        src_2: './images/content/products/2_11_01.avif',
        src_3: './images/content/products/2_11_02.avif',
        src_4: './images/content/products/2_11_04.avif',
        src_5: './images/content/products/2_11_05.avif',
        src_6: './images/content/products/2_11_06.avif',
        src_7: './images/content/products/2_11_07.avif',
        src_8: './images/content/products/2_11_08.avif',
        src_9: './images/content/products/2_11_09.avif',
        src_10: './images/content/products/2_11_10.avif',
        title: "Нож. Совелий",
        subtitle: "Cталь У12",
        descriptionBlade: "Клинок: сталь У12, зонная закалка, твердость 58hrc.",
        descriptionHandle: "Рукоять: Карельская берёза, литьё мельхиор, проставки фибра, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка, финиш.",
        filter: "knives-traditional",
    },
    {
        id: 4_06,
        src_1: './images/content/products/4_06_03.avif',
        src_2: './images/content/products/4_06_04.avif',
        src_3: './images/content/products/4_06_05.avif',
        src_4: './images/content/products/4_06_06.avif',
        src_5: './images/content/products/4_06_01.avif',
        src_6: './images/content/products/4_06_02.avif',
        title: "Топор",
        subtitle: "Сталь ст45, 60с2а",
        descriptionBlade: "Топор: тело ст45, вваренное лезвие 60с2а, твердость 56 hrc.",
        descriptionHandle: "Топорище: бук, пропитка.",
        descriptionScabbard: "Чехол: тиснение, покраска, пропитка восками.",
        filter: "axes",
    },
    {
        id: 4_02,
        src_1: './images/content/gallery/4_02.avif',
        src_2: './images/content/products/4_02_02.avif',
        title: "Ножи метательные",
        subtitle: "Сталь 60с2а",
        descriptionBlade: "Клинок: сталь 60с2а, закалка 54 hrc.",
        descriptionHandle: "",
        descriptionScabbard: "",
        filter: "other",
    },
    {
        id: 3_03,
        src_1: './images/content/products/3_03_03.avif',
        src_2: './images/content/products/3_03_02.avif',
        src_3: './images/content/gallery/3_03.avif',
        src_4: './images/content/products/3_03_04.avif',
        src_5: './images/content/products/3_03_05.avif',
        src_6: './images/content/products/3_03_06.avif',
        title: "Ножи кухонные",
        subtitle: "Сталь 95х18",
        descriptionBlade: "Клинок: сталь 95х18, закалка 57 hrc.",
        descriptionHandle: "Рукоять: Чёрный граб, латунь.",
        descriptionScabbard: "",
        filter: "knives-kitchen",
    },
    {
        id: 3_01,
        src_1: './images/content/gallery/3_01.avif',
        src_2: './images/content/products/3_01_02.avif',
        src_3: './images/content/products/3_01_03.avif',
        src_4: './images/content/products/3_01_04.avif',
        src_5: './images/content/products/3_01_05.avif',
        src_6: './images/content/products/3_01_06.avif',
        src_7: './images/content/products/3_01_07.avif',
        src_8: './images/content/products/3_01_08.avif',
        src_9: './images/content/products/3_01_09.avif',
        title: "Ножи кухонные",
        subtitle: "Сталь 95х18",
        descriptionBlade: "Клинок: сталь 95х18, закалка 56 hrc.",
        descriptionHandle: "Рукоять: Карельская берёза, амарант, латунь.",
        descriptionScabbard: "",
        filter: "knives-kitchen",
    },
    {
        id: 3_02,
        src_1: './images/content/gallery/3_02.avif',
        src_2: './images/content/products/3_02_02.avif',
        src_3: './images/content/products/3_02_03.avif',
        src_4: './images/content/products/3_02_04.avif',
        src_5: './images/content/products/3_02_05.avif',
        src_6: './images/content/products/3_02_06.avif',
        src_7: './images/content/products/3_02_07.avif',
        src_8: './images/content/products/3_02_08.avif',
        src_9: './images/content/products/3_02_09.avif',
        title: "Ножи кухонные",
        subtitle: "Сталь 440с",
        descriptionBlade: "Клинок: сталь 440с, закалка 56 hrc.",
        descriptionHandle: "Рукоять: Карельская берёза, амарант, латунь.",
        descriptionScabbard: "",
        filter: "knives-kitchen",
    },
    {
        id: 1_01,
        src_1: './images/content/gallery/1_01.avif',
        src_2: './images/content/products/1_01_02.avif',
        title: "Нож-подвеска Шебутной",
        subtitle: "Сталь х12мф",
        descriptionBlade: "Клинок: сталь х12мф, обработка клинка stonewash, закалка 59 hrc.",
        descriptionHandle: "",
        descriptionScabbard: "Ножны: кожа, тиснение, покраска, пропитка.",
        filter: "knives-mini",
    },
    {
        id: 4_05,
        src_1: './images/content/gallery/4_05.avif',
        src_2: './images/content/products/4_05_02.avif',
        src_3: './images/content/products/4_05_03.avif',
        src_4: './images/content/products/4_05_04.avif',
        title: "Топорик (брелок)",
        subtitle: "Сталь ст3",
        descriptionBlade: "Топор: сталь ст3.",
        descriptionHandle: "Топорище: Бук",
        descriptionScabbard: "",
        filter: "other",
    },
    {
        id: 1_04,
        src_1: './images/content/gallery/1_04.avif',
        src_2: './images/content/products/1_04_02.avif',
        src_3: './images/content/products/1_04_03.avif',
        src_4: './images/content/products/1_04_04.avif',
        src_5: './images/content/products/1_04_05.avif',
        title: "Нож-подвеска",
        subtitle: "Сталь у12а",
        descriptionBlade: "Клинок: сталь у12а, твердость 61hrc.",
        descriptionHandle: "Рукоять: карельская берёза, патинированная бронза, поставка фибра, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка, финиш.",
        filter: "knives-mini",
    },
    {
        id: 6_01,
        src_1: './images/content/products/6_01_01.avif',
        src_2: './images/content/products/6_01_02.avif',
        src_3: './images/content/products/6_01_03.avif',
        src_4: './images/content/products/6_01_04.avif',
        src_5: './images/content/products/6_01_05.avif',
        title: "Нож",
        subtitle: "Сталь у10",
        descriptionBlade: "Клинок: сталь у10 ,твердость 57hrc.",
        descriptionHandle: "Рукоять: чёрный граб, патинированная бронза, проставка фибра, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка, финиш.",
        filter: "knives-traditional",
    },
    {
        id: 6_03,
        src_1: './images/content/products/6_03_01.avif',
        src_2: './images/content/products/6_03_02.avif',
        src_3: './images/content/products/6_03_03.avif',
        src_4: './images/content/products/6_03_04.avif',
        src_5: './images/content/products/6_03_05.avif',
        src_6: './images/content/products/6_03_06.avif',
        src_7: './images/content/products/6_03_07.avif',
        title: "Нож",
        subtitle: "Дамасская сталь",
        descriptionBlade: "Клинок: дамаск ,твердость 61hrc.",
        descriptionHandle: "Рукоять: карельская берёза с эффектом изменения цвета, патинированная бронза, проставка фибра, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка, тиснение, финиш.",
        filter: "knives-traditional, damask-steel",
    },
    {
        id: 6_04,
        src_1: './images/content/products/6_04_01.avif',
        src_2: './images/content/products/6_04_02.avif',
        src_3: './images/content/products/6_04_03.avif',
        src_4: './images/content/products/6_04_04.avif',
        title: "Нож",
        subtitle: "Сталь шх15",
        descriptionBlade: "Клинок: сталь шх15,зонная закалка, твердость 59 hrc.",
        descriptionHandle: "Рукоять: карельская берёза с эффектом изменения цвета, патинированная бронза, проставка фибра, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка, тиснение, финиш.",
        filter: "knives-traditional",
    },
    {
        id: 6_05,
        src_1: './images/content/products/6_05_01.avif',
        src_2: './images/content/products/6_05_02.avif',
        src_3: './images/content/products/6_05_03.avif',
        src_4: './images/content/products/6_05_04.avif',
        src_5: './images/content/products/6_05_05.avif',
        src_6: './images/content/products/6_05_06.avif',
        src_7: './images/content/products/6_05_07.avif',
        title: "Нож",
        subtitle: "Дамасская сталь",
        descriptionBlade: "Клинок: дамаск ,твердость 62hrc.",
        descriptionHandle: "Рукоять: стабилизированная карельская берёза, патинированный мельхиор, проставка фибра, финиш.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка, финиш.",
        filter: "knives-traditional, damask-steel",
    },
    {
        id: 6_07,
        src_1: './images/content/products/6_07_01.avif',
        src_2: './images/content/products/6_07_02.avif',
        src_3: './images/content/products/6_07_03.avif',
        src_4: './images/content/products/6_07_04.avif',
        title: "Нож",
        subtitle: "Сталь шх15",
        descriptionBlade: "Клинок: сталь шх15,зонная закалка, твердость 58 hrc.",
        descriptionHandle: "Рукоять: орех, чёрный граб, патинированная бронза, проставки, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка, тиснение.",
        filter: "knives-traditional",
    },
    {
        id: 6_06,
        src_1: './images/content/products/6_06_01.avif',
        src_2: './images/content/products/6_06_02.avif',
        src_3: './images/content/products/6_06_03.avif',
        src_4: './images/content/products/6_06_04.avif',
        src_5: './images/content/products/6_06_05.avif',
        title: "Нож",
        subtitle: "Сталь шх15",
        descriptionBlade: "Клинок: сталь шх15,зонная закалка, твердость 60 hrc.",
        descriptionHandle: "Рукоять: стабилизированная карельская берёза, патинированная бронза, проставка фибра, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка, тиснение, финиш.",
        filter: "knives-traditional",
    },
    {
        id: 3_05,
        src_1: './images/content/gallery/3_05.avif',
        src_2: './images/content/products/3_05_02.avif',
        src_3: './images/content/products/3_05_03.avif',
        src_4: './images/content/products/3_05_04.avif',
        src_5: './images/content/products/3_05_05.avif',
        src_6: './images/content/products/3_05_06.avif',
        src_7: './images/content/products/3_05_07.avif',
        src_8: './images/content/products/3_05_08.avif',
        title: "Шеф-нож",
        subtitle: "Сталь 440с",
        descriptionBlade: "Клинок: сталь 440с, твердость 57 hrc.",
        descriptionHandle: "Рукоять: стабилизированная карельская берёза, штифты - нержавеющая сталь, фибра.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка, финиш.",
        filter: "knives-kitchen",
    },
    {
        id: 7_01,
        src_1: './images/content/products/7_01_01.avif',
        src_2: './images/content/products/7_01_02.avif',
        src_3: './images/content/products/7_01_03.avif',
        src_4: './images/content/products/7_01_04.avif',
        src_5: './images/content/products/7_01_05.avif',
        src_6: './images/content/products/7_01_06.avif',
        title: "Нож. Финка",
        subtitle: "Сталь 50хфа",
        descriptionBlade: "Клинок: сталь 50хфа, зонная закалка, твердость 58 hrc.",
        descriptionHandle: "Рукоять: чёрный граб, патинированная бронза, проставки, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка, тиснение.",
        filter: "knives-traditional",
    },
    {
        id: 7_02,
        src_1: './images/content/products/7_02_01.avif',
        src_2: './images/content/products/7_02_02.avif',
        src_3: './images/content/products/7_02_03.avif',
        src_4: './images/content/products/7_02_04.avif',
        src_5: './images/content/products/7_02_05.avif',
        src_6: './images/content/products/7_02_06.avif',
        src_7: './images/content/products/7_02_07.avif',
        src_8: './images/content/products/7_02_08.avif',
        title: "Нож",
        subtitle: "Сталь х12мф",
        descriptionBlade: "Клинок: сталь х12мф, узор, твердость 61 hrc.",
        descriptionHandle: "Рукоять: мербау, чёрный граб, патинированная бронза, проставки, пропитка.",
        descriptionScabbard: "Ножны: тиснение, покраска, пропитка.",
        descriptionBelt: "Ремень: тиснение, пропитка, покраска. Размер 1200мм на 48мм. Пряжка: торцовый мозаичный дамаск, воронение.",
        filter: "knives-traditional",
    },
    {
        id: 7_03,
        src_1: './images/content/products/7_03_01.avif',
        src_2: './images/content/products/7_03_02.avif',
        src_3: './images/content/products/7_03_03.avif',
        src_4: './images/content/products/7_03_04.avif',
        src_5: './images/content/products/7_03_05.avif',
        src_6: './images/content/products/7_03_06.avif',
        src_7: './images/content/products/7_03_07.avif',
        src_8: './images/content/products/7_03_08.avif',
        src_9: './images/content/products/7_03_09.avif',
        title: "Нож",
        subtitle: "Сталь У8",
        descriptionBlade: "Клинок: сталь У8, зонная закалка, хамон, твердость 60 hrc.",
        descriptionHandle: "Рукоять: карельская берёза, патинированная бронза, проставки, пропитка.",
        descriptionScabbard: "Ножны: покраска, пропитка, тиснение.",
        filter: "knives-traditional",
    },
    {
        id: 7_04,
        src_1: './images/content/products/7_04_01.avif',
        src_2: './images/content/products/7_04_02.avif',
        src_3: './images/content/products/7_04_03.avif',
        src_4: './images/content/products/7_04_04.avif',
        src_5: './images/content/products/7_04_05.avif',
        src_6: './images/content/products/7_04_06.avif',
        src_7: './images/content/products/7_04_07.avif',
        src_8: './images/content/products/7_04_08.avif',
        src_9: './images/content/products/7_04_09.avif',
        title: "Нож",
        subtitle: "Сталь У8",
        descriptionBlade: "Клинок: сталь У8, зонная закалка, хамон, твердость 60 hrc.",
        descriptionHandle: "Рукоять: карельская берёза, патинированная бронза, проставка, пропитка.",
        descriptionScabbard: "Ножны: липовый вкладыш, покраска, пропитка.",
        filter: "knives-traditional",
    },
    {
        id: 8_01,
        src_1: './images/content/products/8_01_01.avif',
        src_2: './images/content/products/8_01_02.avif',
        src_3: './images/content/products/8_01_03.avif',
        src_4: './images/content/products/8_01_04.avif',
        src_5: './images/content/products/8_01_05.avif',
        src_6: './images/content/products/8_01_06.avif',
        src_7: './images/content/products/8_01_07.avif',
        title: "Нож",
        subtitle: "Сталь х12мф",
        descriptionBlade: "Клинок: сталь х12мф, булатный узор, твердость 61 hrc.",
        descriptionHandle: "Рукоять: амарант, литьё (Сталин), мельхиор, проставки, пропитка.",
        descriptionScabbard: "Ножны: тиснение,покраска,пропитка.",
        filter: "knives-traditional",
    },
    {
        id: 7_06,
        src_1: './images/content/products/7_06_01.avif',
        src_2: './images/content/products/7_06_02.avif',
        src_3: './images/content/products/7_06_03.avif',
        src_4: './images/content/products/7_06_04.avif',
        src_5: './images/content/products/7_06_05.avif',
        src_6: './images/content/products/7_06_06.avif',
        src_7: './images/content/products/7_06_07.avif',
        src_8: './images/content/products/7_06_08.avif',
        title: "Нож",
        subtitle: "Сталь У8",
        descriptionBlade: "Клинок: сталь У8, зонная закалка, хамон, булатный узор, твердость 60 hrc.",
        descriptionHandle: "Рукоять: карельская берёза, бронза, проставки, пропитка.",
        descriptionScabbard: "Ножны: тиснение, покраска, пропитка.",
        filter: "knives-traditional",
    },
    {
        id: 7_07,
        src_1: './images/content/products/7_07_01.avif',
        src_2: './images/content/products/7_07_02.avif',
        src_3: './images/content/products/7_07_03.avif',
        src_4: './images/content/products/7_07_04.avif',
        title: "Нож. Финка",
        subtitle: "Сталь У8",
        descriptionBlade: "Клинок: сталь У8, зонная закалка, твердость 58 hrc.",
        descriptionHandle: "Рукоять: чёрный граб, бронза, проставки, пропитка.",
        descriptionScabbard: "Ножны: кожа, покраска, пропитка.",
        filter: "knives-traditional",
    },
    {
        id: 7_08,
        src_1: './images/content/products/7_08_01.avif',
        src_2: './images/content/products/7_08_02.avif',
        src_3: './images/content/products/7_08_03.avif',
        src_4: './images/content/products/7_08_04.avif',
        src_5: './images/content/products/7_08_05.avif',
        src_6: './images/content/products/7_08_06.avif',
        src_7: './images/content/products/7_08_07.avif',
        src_8: './images/content/products/7_08_08.avif',
        title: "Нож",
        subtitle: "Сталь шх15",
        descriptionBlade: "Клинок: сталь шх15,зонная закалка, твердость 61 hrc.",
        descriptionHandle: "Рукоять: корень ореха, проставки, пропитка, бронза.",
        descriptionScabbard: "Ножны: тиснение, покраска, пропитка.",
        filter: "knives-traditional",
    },
    {
        id: 7_09,
        src_1: './images/content/products/7_09_01.avif',
        src_2: './images/content/products/7_09_02.avif',
        src_3: './images/content/products/7_09_03.avif',
        src_4: './images/content/products/7_09_04.avif',
        src_5: './images/content/products/7_09_05.avif',
        src_6: './images/content/products/7_09_06.avif',
        title: "Нож",
        subtitle: "Сталь У8",
        descriptionBlade: "Клинок: сталь У8, зонная закалка, твердость 58 hrc.",
        descriptionHandle: "Рукоять: карельская берёза, бронза, латунь, проставки, пропитка.",
        descriptionScabbard: "Ножны: тиснение, покраска, пропитка.",
        filter: "knives-traditional",
    },
    {
        id: 7_10,
        src_1: './images/content/products/7_10_01.avif',
        src_2: './images/content/products/7_10_02.avif',
        src_3: './images/content/products/7_10_03.avif',
        src_4: './images/content/products/7_10_04.avif',
        src_5: './images/content/products/7_10_05.avif',
        src_6: './images/content/products/7_10_06.avif',
        title: "Топор",
        subtitle: "Сталь ст45",
        descriptionBlade: "Тело: сталь ст45, вваренное лезвие 60с2а, твердость 57 hrc.",
        descriptionHandle: "Топорище: бук, нарезка, пропитка.",
        descriptionScabbard: "",
        filter: "axes",
    },
    {
        id: 7_05,
        src_1: './images/content/products/7_05_09.avif',
        src_2: './images/content/products/7_05_01.avif',
        src_3: './images/content/products/7_05_02.avif',
        src_4: './images/content/products/7_05_03.avif',
        src_5: './images/content/products/7_05_04.avif',
        src_6: './images/content/products/7_05_05.avif',
        src_7: './images/content/products/7_05_06.avif',
        src_8: './images/content/products/7_05_07.avif',
        src_9: './images/content/products/7_05_08.avif',
        title: "Топор",
        subtitle: "Сталь ст45, 60с2а",
        descriptionBlade: "Тело: сталь ст45, вваренное лезвие 60с2а, твердость 57 hrc.",
        descriptionHandle: "Топорище: бук, нарезка, пропитка.",
        descriptionScabbard: "Чехол: тиснение, покраска, пропитка.",
        filter: "axes",
    },
    {
        id: 8_02,
        src_1: './images/content/products/8_02_01.avif',
        src_2: './images/content/products/8_02_02.avif',
        src_3: './images/content/products/8_02_03.avif',
        src_4: './images/content/products/8_02_04.avif',
        src_5: './images/content/products/8_02_05.avif',
        title: "Нож",
        subtitle: "Сталь х12мф",
        descriptionBlade: "Клинок: сталь х12мф, булатный узор, твердость 61 hrc.",
        descriptionHandle: "Рукоять: карельская берёза, бронза, латунь, патинирование, проставка орех, пропитка.",
        descriptionScabbard: "Ножны: тиснение, покраска, пропитка.",
        filter: "knives-traditional",
    },
    {
        id: 8_03,
        src_1: './images/content/products/8_03_01.avif',
        src_2: './images/content/products/8_03_02.avif',
        src_3: './images/content/products/8_03_03.avif',
        title: "Нож",
        subtitle: "Дамасская сталь",
        descriptionBlade: "Клинок: дамасская сталь у8+шх15, твердость 56 hrc.",
        descriptionHandle: "Рукоять: падук, бронза, проставки, пропитка.",
        descriptionScabbard: "Ножны: тиснение, покраска, пропитка.",
        filter: "knives-traditional, damask-steel",
    },
    {
        id: 8_04,
        src_1: './images/content/products/8_04_01.avif',
        src_2: './images/content/products/8_04_02.avif',
        src_3: './images/content/products/8_04_03.avif',
        src_4: './images/content/products/8_04_04.avif',
        title: "Нож",
        subtitle: "Дамасская сталь",
        descriptionBlade: "Клинок: дамасская сталь у8+шх15, твердость 56 hrc.",
        descriptionHandle: "Рукоять: зебрано, мельхиор, проставки, пропитка.",
        descriptionScabbard: "Ножны разборные (съемная петля): тиснение, покраска, пропитка.",
        filter: "knives-traditional, damask-steel",
    },
    {
        id: 8_05,
        src_1: './images/content/products/8_05_01.avif',
        src_2: './images/content/products/8_05_02.avif',
        src_3: './images/content/products/8_05_03.avif',
        src_4: './images/content/products/8_05_04.avif',
        src_5: './images/content/products/8_05_05.avif',
        title: "Нож",
        subtitle: "Сталь У8",
        descriptionBlade: "Клинок: сталь у8, зонная закалка, твердость 57 hrc.",
        descriptionHandle: "Рукоять: берёза, бронза, проставки, пропитка.",
        descriptionScabbard: "Ножны: тиснение, покраска, пропитка.",
        filter: "knives-traditional",
    },
    {
        id: 8_06,
        src_1: './images/content/products/8_06_01.avif',
        src_2: './images/content/products/8_06_02.avif',
        src_3: './images/content/products/8_06_03.avif',
        src_4: './images/content/products/8_06_04.avif',
        src_5: './images/content/products/8_06_05.avif',
        src_6: './images/content/products/8_06_06.avif',
        title: "Нож",
        subtitle: "Сталь шх15",
        descriptionBlade: "Клинок: сталь шх15, зонная закалка, булатный узор, твердость 59 hrc.",
        descriptionHandle: "Рукоять: чёрный граб, бронза, проставки.",
        descriptionScabbard: "Ножны: тиснение, пропитка.",
        filter: "knives-traditional",
    },
    {
        id: 8_07,
        src_1: './images/content/products/8_07_01.avif',
        src_2: './images/content/products/8_07_02.avif',
        src_3: './images/content/products/8_07_03.avif',
        src_4: './images/content/products/8_07_04.avif',
        src_5: './images/content/products/8_07_05.avif',
        src_6: './images/content/products/8_07_06.avif',
        title: "Нож",
        subtitle: "Сталь шх15",
        descriptionBlade: "Клинок: сталь шх15, зонная закалка, хамон, твердость 60 hrc.",
        descriptionHandle: "Рукоять: карельская береза, мельхиор.",
        descriptionScabbard: "Ножны разборные (съемная петля): пропитка,тиснение.",
        filter: "knives-traditional",
    },
    {
        id: 8_08,
        src_1: './images/content/products/8_08_01.avif',
        src_2: './images/content/products/8_08_02.avif',
        src_3: './images/content/products/8_08_03.avif',
        src_4: './images/content/products/8_08_04.avif',
        title: "Мини-нож",
        subtitle: "Сталь у8",
        descriptionBlade: "Клинок: сталь у8, зонная закалка, твердость 60 hrc.",
        descriptionHandle: "Рукоять: джинсовая микарта.",
        descriptionScabbard: "",
        filter: "knives-mini",
    },
    {
        id: 8_09,
        src_1: './images/content/products/8_09_01.avif',
        src_2: './images/content/products/8_09_02.avif',
        src_3: './images/content/products/8_09_03.avif',
        src_4: './images/content/products/8_09_04.avif',
        src_5: './images/content/products/8_09_05.avif',
        src_6: './images/content/products/8_09_06.avif',
        src_7: './images/content/products/8_09_07.avif',
        title: "Нож",
        subtitle: "Сталь шх15",
        descriptionBlade: "Клинок: сталь шх15, зонная закалка, хамон, твердость 62 hrc.",
        descriptionHandle: "Рукоять: корень ореха, бронза, мельхиор.",
        descriptionScabbard: "Ножны: тиснение, покраска, пропитка.",
        filter: "knives-traditional",
    },
    {
        id: 9_01,
        src_1: './images/content/products/9_01_01.avif',
        src_2: './images/content/products/9_01_02.avif',
        src_3: './images/content/products/9_01_03.avif',
        title: "Топор",
        subtitle: "Сталь ст3, 60с2а",
        descriptionBlade: "Тело: сталь ст3, вваренное лезвие 60с2а, твердость 56 hrc.",
        descriptionHandle: "Древко: бук, 105см",
        descriptionScabbard: "",
        filter: "axes",
    },
    {
        id: 9_06,
        src_1: './images/content/products/9_06_01.avif',
        src_2: './images/content/products/9_06_02.avif',
        src_3: './images/content/products/9_06_03.avif',
        src_4: './images/content/products/9_06_04.avif',
        title: "Тантоноид",
        subtitle: "Сталь шх15",
        descriptionBlade: "Клинок: сталь шх15, зонная закалка, хамон, булатный узор, твердость 59 hrc.",
        descriptionHandle: "",
        descriptionScabbard: "",
        filter: "other",
    },
    {
        id: 9_02,
        src_1: './images/content/products/9_02_01.avif',
        src_2: './images/content/products/9_02_02.avif',
        title: "Меч",
        subtitle: "Сталь 60с2",
        descriptionBlade: "Клинок: сталь 60с2, твердость 52 hrc.",
        descriptionHandle: "",
        descriptionScabbard: "",
        filter: "other",
    },
    {
        id: 9_03,
        src_1: './images/content/products/9_03_01.avif',
        src_2: './images/content/products/9_03_02.avif',
        src_3: './images/content/products/9_03_03.avif',
        src_4: './images/content/products/9_03_04.avif',
        src_5: './images/content/products/9_03_05.avif',
        src_6: './images/content/products/9_03_06.avif',
        title: "Нож",
        subtitle: "Сталь шх15",
        descriptionBlade: "Клинок: сталь шх15, зонная закалка, хамон, булатный узор, твердость 61 hrc.",
        descriptionHandle: "Рукоять: клён, резьба Владимира Калуцких",
        descriptionScabbard: "Ножны: пропитка, тиснение.",
        filter: "knives-traditional",
    },
    {
        id: 9_04,
        src_1: './images/content/products/9_04_01.avif',
        src_2: './images/content/products/9_04_02.avif',
        src_3: './images/content/products/9_04_03.avif',
        src_4: './images/content/products/9_04_04.avif',
        src_5: './images/content/products/9_04_05.avif',
        src_6: './images/content/products/9_04_06.avif',
        title: "Нож",
        subtitle: "Сталь шх15",
        descriptionBlade: "Клинок: сталь шх15, зонная закалка, хамон, булатный узор, твердость 60 hrc.",
        descriptionHandle: "",
        descriptionScabbard: "Ножны: пропитка, тиснение.",
        filter: "knives-traditional",
    },
    {
        id: 9_05,
        src_1: './images/content/products/9_05_01.avif',
        src_2: './images/content/products/9_05_02.avif',
        src_3: './images/content/products/9_05_03.avif',
        src_4: './images/content/products/9_05_04.avif',
        title: "Нож. Скандинав",
        subtitle: "Сталь шх15",
        descriptionBlade: "Клинок: сталь шх15, зонная закалка, хамон, твердость 58 hrc.",
        descriptionHandle: "",
        descriptionScabbard: "Ножны: пропитка, тиснение.",
        filter: "knives-traditional",
    },
];

